version: '3.1'

services:
  jrtb:
    depends_on:
      -jrtb-db
    build:
      context: .
    env_file:
      - ./.env/jrtb.env
    restart: always
  jrtb-db:
    image: mysql:5.7
    restart: always
    env_file:
      - ./.env/jrtb.env
    ports:
      - "3308:3306"

